assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: ''

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

ga_analytics: UA-XXXXXXXX-X

gems:
  - jekyll-assets
  - jekyll-sitemap

name: ux_site

permalink: pretty

url: # add site url


# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  components:
    output: true
    permalink: components/:path/

# Title
name: PR Newswire UX
subtitle: UX site

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
# baseurl: '/DOCter'

# Author/Organization info to be displayed in the templates
author:
  name: Name
  url: http://localhost:4000

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Analytics
  url: analytics/
  internal: true
- text: Development Environment Guide
  url: development-environment-guide/
  internal: true
- text: Accessibility
  url: accessibility/
  internal: true
- text: Guides Template
  url: guide-template/
  internal: true
- text: Design Methods
  url: design-methods/
  internal: true
- text: Testing Cookbook
  url: testing-cookbook/
  internal: true
- text: Agile
  url: agile/
  internal: true
- text: Lean Product Design
  url: lean-product-design/
  internal: true
- text: Joining UX
  url: joining-ux/
  internal: true
- text: Style guide
  url: style-guide/
  internal: true
- text: Content Guide
  url: content-guide/
  internal: true
- text: Blog
  url: blog/
  internal: true

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: ux_site
  description: PR Newswire UX site
  url: https://github.com/prnewswire-ux/ux_site

# Style Variables
brand_color: "#47536b"

# Offline caching
offline_cache: false
cache_name: prnux-v1.1